version: '3.5'

services:
    app_php:
        image: docker.io/chmelik/k8s-workshop-app-php:0.1
        #build:
        #    target: app_php
        restart: unless-stopped
        depends_on:
            - app_database

    app_webserver:
        image: docker.io/chmelik/k8s-workshop-app-webserver:0.1
        #build:
        #    target: nginx
        volumes:
            - ./docker/ssl:/etc/nginx/ssl:ro
        depends_on:
            - app_php
        ports:
            - '443:443'

    app_database:
        image: postgres:${POSTGRES_VERSION:-14.5}-alpine
        restart: unless-stopped
        volumes:
            - app_database:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-db_name}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db_password}
            POSTGRES_USER: ${POSTGRES_USER:-db_user}

volumes:
    app_database:
        name: ${COMPOSE_PROJECT_NAME}_app_database
