apiVersion: v1
kind: Service
metadata:
  name: app-database-dev-access
  namespace: k8s-workshop
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 54321
      targetPort: 5432
  selector:
    app: database
