apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv-claim-database
  namespace: k8s-workshop
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
