apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-webserver
  namespace: k8s-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: docker.io/chmelik/k8s-workshop-app-webserver:0.5
          env:
            - name: APP_PHP_HOST
              value: app-php-srv
          ports:
            - containerPort: 80
          #volumeMounts:
          #  - name: nginx-config-storage
          #    mountPath: /etc/nginx/conf.d/default.conf
          #    subPath: default.conf
      restartPolicy: Always
      #volumes:
      #  - name: nginx-config-storage
      #    configMap:
      #      name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-webserver-srv
  namespace: k8s-workshop
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: webserver
