apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: another-pv-claim-php
  namespace: k8s-workshop
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
