apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv-volume
  labels:
    type: local
spec:
  #storageClassName: manual slow ssd
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
